/**
 * The Doctor Handoff Timeline card (§5.3).
 *
 * A structured clinical alert card, not a chat transcript — readable by a
 * doctor in seconds.
 *
 * THE CONSTRAINT THAT SHAPES THIS FILE: §5.3 requires severity and
 * classification to trace back to Infermedica's output rather than being
 * freeform-generated by Groq, "to keep the handoff clinically defensible".
 * So the clinical fields are not free properties that any code path could set.
 * They live in `derived`, whose only constructor takes a `RiskAssessment` —
 * there is no way to hand-assemble a card with an invented severity score.
 * Groq's contribution is confined to `narrative`, which carries no numbers.
 */

import type { IsoTimestamp, Language } from './common.js';
import type { ConfidenceLevel } from './confidence.js';
import type { RiskAssessment, RiskTier, TriageLevel } from './risk.js';
import { severityScore } from './risk.js';
import type { RoutingOutcome } from './routing.js';
import type { TimelineEntry } from './timeline.js';

/** Standardised condition code from the WHO ICD-11 API (§6). */
export interface Icd11Code {
  readonly code: string;
  readonly title: string;
  readonly uri?: string;
  /**
   * Always true: the code reflects the Infermedica-derived category. The system
   * does not independently diagnose. Present as a field so the UI can state it.
   */
  readonly derivedFromTriageCategory: true;
}

/**
 * Clinical fields, all traceable to the scoring engine. Build only via
 * `deriveClinicalFields`.
 */
export interface DerivedClinicalFields {
  readonly severityOutOfTen: number;
  readonly triageLevel: TriageLevel;
  readonly riskTier: RiskTier;
  /**
   * "Classic presentation" flag (§5.3) — set when the scoring engine itself
   * flagged evidence as serious/emergency, not when a model thought it looked
   * textbook.
   */
  readonly classicPresentation: boolean;
  readonly classicPresentationBasis: readonly string[];
  readonly scoringSource: RiskAssessment['source'];
  /** Present when the score came from the local fallback. Printed on the card. */
  readonly scoringDegradedReason?: string;
  readonly scoredAt: IsoTimestamp;
}

/**
 * The ONLY way to produce `DerivedClinicalFields`. Every clinical number on the
 * card comes out of the assessment; nothing here accepts a caller-supplied
 * severity.
 */
export function deriveClinicalFields(
  assessment: RiskAssessment,
): DerivedClinicalFields {
  const seriousFlags = assessment.seriousFlags;
  const base = {
    severityOutOfTen: severityScore(assessment),
    triageLevel: assessment.triageLevel,
    riskTier: assessment.tier,
    classicPresentation: seriousFlags.length > 0 || assessment.triageTuples.length > 0,
    classicPresentationBasis: [
      ...seriousFlags.map((f) => f.commonName ?? f.name),
      ...assessment.triageTuples.map((t) => t.label),
    ],
    scoringSource: assessment.source,
    scoredAt: assessment.computedAt,
  };
  return assessment.degradedReason === undefined
    ? base
    : { ...base, scoringDegradedReason: assessment.degradedReason };
}

/** Free-text fields. Groq may write these. None of them carry a clinical number. */
export interface HandoffNarrative {
  /** One line. e.g. "Central chest pain radiating to left arm, 5 minutes". */
  readonly chiefComplaint: string;
  /** Short paragraph of context — no scores, no classifications. */
  readonly contextNote?: string;
}

export interface DoctorHandoffCard {
  readonly caseId: string;

  readonly narrative: HandoffNarrative;
  readonly derived: DerivedClinicalFields;

  /** When symptoms began, from reported onset — not when the app was opened. */
  readonly onsetAt?: IsoTimestamp;
  /** Minutes from onset to handoff. The number a clinician reaches for first. */
  readonly elapsedMinutes?: number;

  /** The patient's own words, verbatim (§5.3). Never paraphrased. */
  readonly patientQuotes: readonly string[];

  readonly detectedLanguage: Language;
  readonly interpretedFrom?: Language;

  /** Clinically significant entries only, chronological. */
  readonly highlights: readonly TimelineEntry[];

  readonly recommendedRouting: RoutingOutcome;
  /** Low confidence is printed on the card so the clinician knows to re-verify. */
  readonly informationConfidence: ConfidenceLevel;
  readonly unresolvedContradictionCount: number;

  readonly icd11?: Icd11Code;

  /** Allergies, current medications (RxNorm-normalised), chronic conditions. */
  readonly allergies: readonly string[];
  readonly medications: readonly string[];
  readonly chronicConditions: readonly string[];
  readonly bloodGroup?: string;

  readonly generatedAt: IsoTimestamp;
  /**
   * Required banner text. This is decision support in a simulated environment,
   * not a diagnosis (§1 guardrail). Rendered on the card, not implied.
   */
  readonly disclaimer: string;
}

export const HANDOFF_DISCLAIMER =
  'Decision support only — generated in a simulated environment. ' +
  'Not a medical diagnosis. Risk classification produced by a deterministic ' +
  'clinical scoring engine; all clinical judgement remains with the attending clinician.';

/** Red banner treatment on the card (§9). */
export function isUrgentCard(card: Pick<DoctorHandoffCard, 'derived'>): boolean {
  return card.derived.riskTier === 'red';
}
